=== BackupTheBerlios/pplt-svn/PPLT/Doc/DTD/PPLT-Device-0.1.dtd
<!ELEMENT PPLTDevice (Head, Setup)>
	<!ELEMENT Head (Description*, Require, Provide)>
	 
		<!ELEMENT Description (#PCDATA)>
	
		<!ELEMENT Require (DCPUModule+, Variable*)>
			<!ELEMENT DCPUModule (#PCDATA)>
			<!ELEMENT Variable (Description*)>

		<!ELEMENT Provide (NameSpace+)>
			<!ELEMENT NameSpace (Slot*,SlotRange*)>
				<!ELEMENT Slot (Description*)>
				<!ELEMENT SlotRange (Description*)>


	<!ELEMENT Setup (Load+)>
		<!ELEMENT Load (Address?, Parameter*, Load*)>
			<!ELEMENT Address (#PCDATA | Variable)*>
			<!ELEMENT Parameter (#PCDATA | Variable)*>
		



<!ATTLIST PPLTDevice 
 name	CDATA	#REQUIRED
 class	CDATA	#REQUIRED
>

<!ATTLIST Description
 lang	CDATA	#REQUIRED
>

<!ATTLIST Variable
 name		CDATA	#REQUIRED
 default	CDATA	#IMPLIED
>

<!ATTLIST NameSpace
 name	CDATA	#REQUIRED
>

<!ATTLIST Slot
 name	CDATA	#REQUIRED
 type	CDATA	#IMPLIED
 mode 	CDATA	#IMPLIED
>

<!ATTLIST SlotRange
 name	CDATA	#REQUIRED
 mode	CDATA	#IMPLIED
 type 	CDATA	#IMPLIED
>

<!ATTLIST Load
 name		CDATA	#REQUIRED
 namespace 	CDATA	#IMPLIED
>

<!ATTLIST Parameter
 name	CDATA	#REQUIRED
>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/PPLT/SIMATIC_S7_200-0.2.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTDevice SYSTEM "PPLT-Device-0.1.dtd">
<PPLTDevice name="S7-200" class="PLC">
    <Head>
		<Description lang="de">Dieses Gerät gibt ihnen die Möglichkeit,
		auf die Merker einer SIMATIC S7 Steuerung zu zugreifen.</Description>
		<Description lang="en">This device gives you access to the markers
		of a SIMATIC S7 PLC.</Description>

        <Require>
            <DCPUModule>Master.Interface.UniSerial</DCPUModule>
            <DCPUModule>Master.Transport.PPI</DCPUModule>
            <DCPUModule>Master.Device.S7</DCPUModule>
			<Variable name="Port" default="0">
				<Description lang="de">Geben sie hier die serielle 
				Schnittstelle an, an die die Steuerung angschlossen ist.
				(0 = COM1(ttyS0), 1 = COM2(ttyS1), ...)</Description>
				<Description lang="en">Put here the number of the
				serial interface. (0 = COM1(ttyS0), 1 = COM2(ttyS1), ...)
				</Description>
			</Variable>
			<Variable name="PCAddr" default="0">
				<Description lang="de">Geben sie hier die Adresse des PCs
				innerhalb des PPI Busses an, (Üblicherweise 0)</Description>
				<Description lang="en">Put here the PPI address of the PC.
				(Norm. 0)</Description> 
			</Variable>
			<Variable name="S7Addr" default="2">
				<Description lang="de">Geben sie hier die PPI Adresse der
				Setuerung an. (Üblicherweise 1..35)</Description>
				<Description lang="en">Put here the PPI address of the PLC.
				(Norm. 1..35)</Description>
			</Variable>
        </Require>

		<Provide>
			<NameSpace name="Marker">
				<SlotRange name="Markers" mode="rw">
					<Description lang="de">Dieser Slot-Bereich gibt ihnen den
					Zugriff auf die Merker der Steuerung. Geben sie hier bitte
					die Adresse der Merkers an, den sie Verwenden wollen.
					</Description>
					<Description lang="en">This slot-range gives you access to
					the markers of the PLC. Please put here the address of the 
					marker you want to use.</Description>
				</SlotRange>
			</NameSpace>
		</Provide>
    </Head>

    
    <Setup>
        <Load name="Master.Interface.UniSerial">
            <Parameter name="Port"><Variable name="Port"/></Parameter>
            <Parameter name="TimeOut">1.0</Parameter>
			<Parameter name="Parity">Even</Parameter>
            <Parameter name="Speed">9600</Parameter>
            <Load name="Master.Transport.PPI">
				<Parameter name="Address"><Variable name="PCAddr"/></Parameter>
				<Load name="Master.Device.S7" namespace="Marker">
					<Address><Variable name="S7Addr"/></Address>
				</Load>
			</Load>
        </Load>
    </Setup>
        
</PPLTDevice>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/Lib/NAiS_FPX-0.2.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTDevice SYSTEM "PPLT-Device-0.1.dtd">
<PPLTDevice name="NAiS-FPX" class="PLC" version="0.3.0">
    <Head>
		<Description lang="de">Dieses Gerät gibt ihnen den Zugriff auf die 
		Merker einer NAiS Steuerung und auf den Modus dieser.</Description>
		<Description lang="en">This device give you access to the makers and
		mode of a NAiS PLC.</Description>

        <Require>
            <DCPUModule>Master.Interface.UniSerial</DCPUModule>
            <DCPUModule>Master.Transport.ReadLine</DCPUModule>
			<DCPUModule>Master.Transport.MEWCOM-TL</DCPUModule>
            <DCPUModule>Master.Device.MEWCOM-CL</DCPUModule>
			<Variable name="Port">
				<Description lang="de">Geben sie hier die serielle 
				Schnittstelle an, an die die Steuerung angschlossen ist.
				0 = COM1(ttyS0), 1 = COM2(ttyS1), ...</Description>
				<Description lang="en">Put here the number of the serial
				interface. 0 = COM1(ttyS0), 1 = COM2(ttyS1), ...
				</Description>
			</Variable>
			<Variable name="Address">
				<Description lang="de">Geben sie hier die Addresse der 
				Steuerung an, die sie ansprechen wollen. (Wenn sie den ToolPort
				verwenden ist diese egal.) Gültige Werte sind die ganzen Zahlen
				zwischen 0 und 255.</Description>
				<Description lang="en">Put here the address of the PLC. (If you
				use the ToolPort you can choose one) Valid values are the 
				numbers between 0 and 255.</Description> 
			</Variable>
        </Require>

		<Provide>
			<NameSpace name="Marker">
				<Slot name="STATUS" type="Bool" mode="rw">
					<Description lang="de">Dieser Slot is Wahr, wenn die 
					Steuerung im RUN modus ist, und Falsch wenn im STOP 
					Modus. Sie können diesen Slot auch schreiben, und somit
					die Steuerung starten und stoppen.</Description>
					<Description lang="en">This Slot is True if the PLC is in
					the RUN mode and False otherwise. You can also write 
					this slot to switch the mode.</Description>
				</Slot>
				<SlotRange name="Marker" mode="rw">
					<Description lang="de">Dieser Slot-Bereich gibt ihnen den 
					Zugriff auf die Merker der Steuerung. Geben sie den Merker 
					an, den sie einbinden möchten.</Description>
					<Description lang="en">This Slot-Range gives you the access
					to the markers of the PLC. Put here the name of the Marker
					you want to bind.</Description>
				</SlotRange>
			</NameSpace>
		</Provide>
    </Head>
    

    <Setup>
        <Load name="Master.Interface.UniSerial">
            <Parameter name="Port"><Variable name="Port"/></Parameter>
            <Parameter name="TimeOut">1.0</Parameter>
			<Parameter name="Parity">Odd</Parameter>
            <Parameter name="Speed">19200</Parameter>
            <Load name="Master.Transport.ReadLine">
				<Parameter name="LineEnd">0D</Parameter>
				<Load name="Master.Transport.MEWCOM-TL">
					<Parameter name="BCC">True</Parameter>
					<Load name="Master.Device.MEWCOM-CL" namespace="Marker">
						<Address><Variable name="Address"/></Address>
					</Load>
				</Load>
            </Load>
        </Load>
    </Setup>
        
</PPLTDevice>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/PPLT/RandomGenerator-0.4.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTDevice SYSTEM "PPLT-Device-0.1.dtd">
<PPLTDevice name="RandomGenerator" class="Debug" version="0.4.0">
	<Head>
		<Description lang="de">
			Der Generator erzeugt Zufallswerte in verschiedenen Type,
			wie Bool, Ganzzahl, Fließkomma.
		</Description>
		<Description lang="en">
			This device generates some random values in several types,
			like bool, integer of floatingpoint.
		</Description>		

		<Require>
			<DCPUModule>Master.Debug.Random</DCPUModule>
		</Require>
		<Provide>
			<NameSpace name="Generator">
				<Slot name="Bool" type="Bool" mode="r">
					<Description lang="de">Boolscher Zufallswert</Description>
					<Description lang="en">Boolean random value</Description>
				</Slot>
				<Slot name="Integer" type="Integer" mode="r">
					<Description lang="de">Zufallswert zischen 0-100</Description>
					<Description lang="en">Random value (0-100)</Description>
				</Slot>
				<Slot name="Float" type="Float" mode="r">
					<Description lang="de">Zufallswert zischen 0-1.0</Description>
					<Description lang="en">Random value (0-1.0)</Description>
				</Slot>
			    <Slot name="String" type="String" mode="r">
                    <Description lang="de">Zufälliger string mit druckbaren Zeichen.</Description>
                    <Description lang="en">Random string with printable characters.</Description>
                </Slot>
                <Slot name="ArrayBool" type="ArrayBool" mode="r">
                    <Description lang="en">Array of random boolean values.</Description>
                    <Description lang="de">Feld mit zufälligen boolschen Werten.
                    </Description>
                </Slot>    
                <Slot name="ArrayInteger" type="ArrayInteger" mode="r">
                    <Description lang="en">Array of random integer values.</Description>
                    <Description lang="de">Feld mit zufälligen ganz-zahligen Werten.
                    </Description>
                </Slot>    
                <Slot name="ArrayFloat" type="ArrayFloat" mode="r">
                    <Description lang="en">Array of random floating-point values.</Description>
                    <Description lang="de">Feld mit zufälligen fließkomma Werten.
                    </Description>
                </Slot>    
                <Slot name="ArrayString" type="ArrayString" mode="r">
                    <Description lang="en">Array of random strings.</Description>
                    <Description lang="de">Feld mit zufälligen Strings.  </Description>
                </Slot>    
                <Slot name="Stream" type="Stream" mode="r">
                    <Description lang="en">Stream of random printable character.</Description>
                    <Description lang="de">Datenstrom aus zufälligen Zeichen.  </Description>
                </Slot>    
                <Slot name="Sequence" type="Sequence" mode="r">
                    <Description lang="en">Sequence of random printable character.</Description>
                    <Description lang="de">Datensequenz aus zufälligen Zeichen.  </Description>
                </Slot>    
            </NameSpace>
		</Provide>
	</Head>
	
	<Setup>
		<Load name="Master.Debug.Random" namespace="Generator"/>
	</Setup>
</PPLTDevice>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/PPLT/GSMMobilePhone-0.3.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTDevice SYSTEM "PPLT-Device-0.1.dtd">
<PPLTDevice name="GSMMobilePhone" class="Mobile" version="0.3.0">
    <Head>
		<Description lang="de">Dieses Gerät bietet den Zugriff auf ein GSM 
		kompatibles Mobiltelefon. Dabei können Werte wie der Herstellername
		oder der Batteriestand abgefragt werden.
		</Description>
		<Description lang="en">This Device provides access to a GSM compatible
		mobilephone. You can read out values like battery-level or 
		manufacturer-name.
		</Description>

		<!-- The require section list all needed modules and variables //-->
        <Require>
            <DCPUModule>Master.Interface.UniSerial</DCPUModule>
            <DCPUModule>Master.Device.GSM</DCPUModule>
        
			<!-- Needed variables(with help) //-->
			<Variable name="Port" default="0">
				<Description lang="de">Die serielle Schnitstelle, an die das 
				Telefon an geschlossen ist. 0 = COM1(ttyS0), 1 = COM2 ...
				</Description>
				<Description lang="en">The serial device the mobile is connected. 
				0 = COM1(ttyS0), 1 = COM2 ...
				</Description>
			</Variable>
			<Variable name="Speed" default="9600">
				<Description lang="de">Die Geschwindigkeit in Baud, die für die 
				Kommunikation mit dem Handy verwendet werden soll. Zum Beispiel
				9600, 19200, 115200.</Description>
				<Description lang="en">The speed in baud to be used for 
				communication with the mobilephone. For example 9600, 19200,
				115200.</Description>
			</Variable>
		</Require>
		
		<!-- The Provide section list and define all NameSpaces //-->
		<Provide>
			<NameSpace name="GSM">
				<!-- define Slot battery with description field //-->
				<Slot name="battery" type="uInteger" mode="r">
					<Description lang="de">Gibt den Batteriestand in Prozent an.</Description>
					<Description lang="en">Shows the battery level.</Description>
				</Slot>
                <Slot name="network" type="uInteger" mode="r">
                    <Description lang="de">Gibt den Netzwerkstatus des Telefons wieder.</Description>
                    <Description lang="en">Returns the network status.</Description>
                </Slot>
				<!-- define Slot quality //-->
				<Slot name="quality" type="uInteger" mode="r">
					<Description lang="de">Gibt die Signalqualität an.</Description>
					<Description lang="en">Shows the signal quality.</Description>
				</Slot>
                <Slot name="errorrate" type="uInteger" mode="r">
                    <Description lang="de">Gibt die Fehlerrate wieder.</Description>
                    <Description lang="en">Returns the error rate.</Description>
                </Slot>
				<!-- define Slot manufacturer //-->
				<Slot name="manufacturer" type="String" mode="r">
					<Description lang="de">Hersteller Name.</Description>
					<Description lang="en">Manufacturer name.</Description>
				</Slot>
				<!-- define Slot model //-->
				<Slot name="model" type="String" mode="r">
					<Description lang="de">Modell-Nummer oder Name</Description>
					<Description lang="en">Model number or name.</Description>
				</Slot>
                <SlotRange name="sms" type="String">
                    <Description lang="de">Sendet eine SMS an den angegebenen Emfänger (Bsp: sms:017012345678)</Description>
                    <Description lang="en">Sends a SMS to the given reciver. (Ex: sms:017012345678)</Description>
                </SlotRange>
			</NameSpace>
		</Provide>
    </Head>


    
    <!-- Description how to load the core modules //-->
	<Setup>
        <Load name="Master.Interface.UniSerial">
            <Parameter name="Port"><Variable name="Port"/></Parameter>
            <Parameter name="TimeOut">2.0</Parameter>
			<Parameter name="Parity">None</Parameter>
            <Parameter name="Speed"><Variable name="Speed"/></Parameter>
            <Load name="Master.Device.GSM" namespace="GSM"/>
        </Load>
    </Setup>
        
</PPLTDevice>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/Lib/RandomGenerator-0.2.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTDevice SYSTEM "PPLT-Device-0.1.dtd">
<PPLTDevice name="RandomGenerator" class="Debug" version="0.3.0">
	<Head>
		<Description lang="de">
			Der Generator erzeugt Zufallswerte in verschiedenen Type,
			wie Bool, Ganzzahl, Flie√ükomma.
		</Description>
		<Description lang="en">
			This device generates some random values in several types,
			like bool, integer of floatingpoint.
		</Description>		

		<Require>
			<DCPUModule>Master.Debug.Random</DCPUModule>
		</Require>
		<Provide>
			<NameSpace name="Generator">
				<Slot name="Bool" type="Bool" mode="r">
					<Description lang="de">Boolscher Zufallswert</Description>
					<Description lang="en">Boolean random value</Description>
				</Slot>
				<Slot name="Byte" type="Byte" mode="r">
					<Description lang="de">Zufallswert zischen 0-100</Description>
					<Description lang="en">Random value (0-100)</Description>
				</Slot>
				<Slot name="Word" type="Word" mode="r">
					<Description lang="de">Zufallswert zischen 0-100</Description>
					<Description lang="en">Random value (0-100)</Description>
				</Slot>
				<Slot name="DWord" type="DWord" mode="r">
					<Description lang="de">Zufallswert zischen 0-100</Description>
					<Description lang="en">Random value (0-100)</Description>
				</Slot>
				<Slot name="Float" type="Float" mode="r">
					<Description lang="de">Zufallswert zischen 0-1.0</Description>
					<Description lang="en">Random value (0-1.0)</Description>
				</Slot>
				<Slot name="Double" type="Double" mode="r">
					<Description lang="de">Zufallswert zischen 0-100</Description>
					<Description lang="en">Random value (0-1.0)</Description>
				</Slot>
			</NameSpace>
		</Provide>
	</Head>
	
	<Setup>
		<Load name="Master.Debug.Random" namespace="Generator"/>
	</Setup>
</PPLTDevice>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/ftp/PPLTModules/Panasonic_FPWEB-0.3.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTDevice SYSTEM "PPLT-Device-0.1.dtd">
<PPLTDevice name="FPWEB" class="PLC" version="0.3.1">
    <Head>
		<Description lang="de">Mit diesem Gerät könenn sie auf die Merker einer
		Panasonic Steuerung zugreifen, die an einen FPWEB-Server angschlossen ist.
		Dazu wird der vom Webserver getunnelte ToolPort benutzt.</Description>
		<Description lang="en">With this device you can access a Panasonic PLC
		that is connected with a Panasonic Webserver. The tunneld ToolPort will be
		used.</Description>
        
		<Require>
            <DCPUModule>Master.Interface.Socket</DCPUModule>
            <DCPUModule>Master.Transport.ReadLine</DCPUModule>
            <DCPUModule>Master.Transport.MEWCOM-TL</DCPUModule>
			<DCPUModule>Master.Device.MEWCOM-CL</DCPUModule>
			<Variable name="NetAddr">
				<Description lang="de">Geben sie hier die Adresse der Webservers und
				den Port des ToolPort-Tunnels (dieser ist meißt 9094) in der Form
				HOSTADDR:PORT an. </Description>
				<Description lang="en">Put here the address and port of the Webserver.
				The port of the tunneld ToolPort is mostly 9094. Form: HOSTADDR:PORT
				</Description>
			</Variable>
			<Variable name="MEWAddr" default="1">
				<Description lang="de">Geben sie hier die Adresse der Steuerung 
				im MEWTOCOL Bus an. Wenn der Webserver mit dem ToolPort des 
				Steuerung verbunden ist, dann ist die Adresse egal. Gültige
				Werte liegen zwischen 1..255.</Description>
				<Description lang="en">Put here the MEWTOCOL address of the 
				PLC. If the webserver is connected to the ToolPort of the 
				PLC you can choos a address. Valid values are 1..255.
				</Description>
			</Variable>
        </Require>
		
		<Provide>
			<NameSpace name="Marker">
				<Slot name="STATUS" type="Bool" mode="rw">
					<Description lang="de">Dieser Slot is Wahr, wenn die 
					Steuerung im RUN modus ist, und Falsch wenn im STOP 
					Modus. Sie können diesen Slot auch schreiben, und somit
					die Steuerung starten und stoppen.</Description>
					<Description lang="en">This Slot is True if the PLC is in
					the RUN mode and False otherwise. You can also write 
					this slot to switch the mode.</Description>
				</Slot>
				<SlotRange name="Marker" mode="rw">
					<Description lang="de">Dieser Slot-Bereich gibt ihnen den 
					Zugriff auf die Merker der Steuerung. Geben sie den Merker 
					an, den sie einbinden möchten.</Description>
					<Description lang="en">This Slot-Range gives you the access
					to the markers of the PLC. Put here the name of the Marker
					you want to bind.</Description>
				</SlotRange>
			</NameSpace>
		</Provide>
    </Head>
    
    <Setup>
        <Load name="Master.Interface.Socket">
            <Parameter name="TimeOut">1.0</Parameter>
            <Load name="Master.Transport.ReadLine">
				<Address><Variable name="NetAddr"/></Address>
				<Parameter name="LineEnd">0D</Parameter>
				<Load name="Master.Transport.MEWCOM-TL">
					<Parameter name="BCC">True</Parameter>
					<Load name="Master.Device.MEWCOM-CL" namespace="Marker">
						<Address><Variable name="MEWAddr"/></Address>
					</Load>
				</Load>
			</Load>
        </Load>
    </Setup>
        
</PPLTDevice>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/PPLT/AGILENT_5462X-0.2.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTDevice SYSTEM "PPLT-Device-0.1.dtd">
<PPLTDevice name="AGILENT-5462X" class="Measure" version="0.3.0">
    <Head>
		<Description lang="de">Mit diesem Gerät, können sie auf die 
		Oszilloskope der 5462-Reihe von Agilent zugreifen und diese steuern.
		Sie können so Messungen veranlassen und die Ergebnisse auslesen. 
		Stellen sie  dazu folgende Parameter beim Oszilloskop ein: 
		(Schnittstelle=seriell, Parität=Keine, Geschwindigkeit=57600,
		Flußkontrolle=RTS/TSR)
		</Description>
		<Description lang="en">With this device you can access the 
		oscilloscopes of the 5462-series by Agilent. So you can init measures		
		and read out the results. Set following parameters on oscilloscope:
		(interface=serial, parity=none, speed=57600, flowcontrol:RTS/TSR)
		</Description>
 
		<Require>
            <DCPUModule>Master.Interface.UniSerial</DCPUModule>
            <DCPUModule>Master.Transport.ReadLine</DCPUModule>
            <DCPUModule>Master.Device.5462X</DCPUModule>
			<Variable name="Port" default="0">
				<Description lang="de">Geben sie hier die serielle 
				Schnittstelle an, an die das Oszilloskop angeschlossen
				ist. (0 = COM1(ttyS0), 1 = COM2(ttyS1), ...)
				</Description>
				<Description lang="en">Put here the number of the serial
				interface. (0 = COM1(ttyS0), 1 = COM2(ttyS1), ...)
				</Description>
			</Variable>
			<Variable name="Primary" default="A1">
				<Description lang="de">Geben die hier die primäre Signalquelle
				an. Zum Beispiel (A1 = erster analog Eingang, A2 = zweiter...)
				</Description>
				<Description lang="en">Put here the primary signalsource. 
				(A1 = first analog input, A2 = second...)
				</Description>
			</Variable>
			<Variable name="Secondary" default="A2">
				<Description lang="de">Geben die hier die sekundäre Signalquelle
				an. Zum Beispiel (A1 = erster analog Eingang, A2 = zweiter...)
				</Description>
				<Description lang="en">Put here the secondary signalsource. 
				(A1 = first analog input, A2 = second...)
				</Description>
			</Variable>
        </Require>

		<Provide>
			<NameSpace name="Values">
				<Slot name="amp" type="Double" mode="r">
					<Description lang="de">Amplitude</Description>
					<Description lang="en">Amplitude</Description>
				</Slot>
				<Slot name="freq" type="Double" mode="r">
					<Description lang="de">Frequenz</Description>
					<Description lang="en">Frequency</Description>
				</Slot>
				<Slot name="phase" type="Double" mode="r">
					<Description lang="de">Phasendifferenz</Description>
					<Description lang="en">Phasediff.</Description>
				</Slot>
				<Slot name="max" type="Double" mode="r"/>
				<Slot name="min" type="Double" mode="r"/>
				<Slot name="pp" type="Double" mode="r"/>
				<Slot name="top" type="Double" mode="r"/>
				<Slot name="base" type="Double" mode="r"/>
				<Slot name="width" type="Double" mode="r"/>
			</NameSpace>			
		</Provide>
    </Head>
    
    <Setup>
        <Load name="Master.Interface.UniSerial">
            <Parameter name="Port"><Variable name="Port"/></Parameter>
            <Parameter name="TimeOut">1.0</Parameter>
			<Parameter name="Parity">None</Parameter>
            <Parameter name="Speed">57600</Parameter>
            <Load name="Master.Transport.ReadLine">
				<Parameter name="LineEnd">0A</Parameter>
            	<Load name="Master.Device.5462X" namespace="Values">
					<Parameter name="PSource"><Variable name="Primary"/></Parameter>
					<Parameter name="SSource"><Variable name="Secondary"/></Parameter>
				</Load>
			</Load>
        </Load>
    </Setup>
        
</PPLTDevice>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/Lib/SIMATIC_S7_200-0.2.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTDevice SYSTEM "PPLT-Device-0.1.dtd">
<PPLTDevice name="S7-200" class="PLC" version="0.3.0">
    <Head>
		<Description lang="de">Dieses Gerät gibt ihnen die Möglichkeit,
		auf die Merker einer SIMATIC S7 Steuerung zu zugreifen.</Description>
		<Description lang="en">This device gives you access to the markers
		of a SIMATIC S7 PLC.</Description>

        <Require>
            <DCPUModule>Master.Interface.UniSerial</DCPUModule>
            <DCPUModule>Master.Transport.PPI</DCPUModule>
            <DCPUModule>Master.Device.S7</DCPUModule>
			<DCPUModule>Master.Debug.Statistic</DCPUModule>

			<Variable name="Port" default="0">
				<Description lang="de">Geben sie hier die serielle 
				Schnittstelle an, an die die Steuerung angschlossen ist.
				(0 = COM1(ttyS0), 1 = COM2(ttyS1), ...)</Description>
				<Description lang="en">Put here the number of the
				serial interface. (0 = COM1(ttyS0), 1 = COM2(ttyS1), ...)
				</Description>
			</Variable>
			<Variable name="PCAddr" default="0">
				<Description lang="de">Geben sie hier die Adresse des PCs
				innerhalb des PPI Busses an, (Üblicherweise 0)</Description>
				<Description lang="en">Put here the PPI address of the PC.
				(Norm. 0)</Description> 
			</Variable>
			<Variable name="S7Addr" default="2">
				<Description lang="de">Geben sie hier die PPI Adresse der
				Setuerung an. (Üblicherweise 1..35)</Description>
				<Description lang="en">Put here the PPI address of the PLC.
				(Norm. 1..35)</Description>
			</Variable>
        </Require>

		<Provide>
			<NameSpace name="Marker">
				<SlotRange name="Markers" mode="rw">
					<Description lang="de">Dieser Slot-Bereich gibt ihnen den
					Zugriff auf die Merker der Steuerung. Geben sie hier bitte
					die Adresse der Merkers an, den sie Verwenden wollen.
					</Description>
					<Description lang="en">This slot-range gives you access to
					the markers of the PLC. Please put here the address of the 
					marker you want to use.</Description>
				</SlotRange>
			</NameSpace>
			<NameSpace name="PPIStatistic">
				<Slot name="read_data" type="DWord" mode="r">
					<Description lang="de">Dieser Slot gibt die Anzahl der empfangenden Bytes wieder.</Description>
					<Description lang="en">This slot gives the number of recived bytes.</Description>
				</Slot>
				<Slot name="write_data" type="DWord" mode="r">
					<Description lang="de">Dieser Slot gibt die Anzahl der gesendeten Bytes wieder.</Description>
					<Description lang="en">This slot gives the number of send bytes.</Description>
				</Slot>
				<Slot name="read_speed" type="DWord" mode="r">
					<Description lang="de">Dieser Slot gibt die Durchschnittsgeschwindigkeit für das lesen an.</Description>
					<Description lang="en">This slot gives the abr. speed for reading.</Description>
				</Slot>
				<Slot name="write_speed" type="DWord" mode="r">
					<Description lang="de">Dieser Slot gibt die Durchschnittsgeschwindigkeit für das Schreiben an.</Description>
					<Description lang="en">This slot gives the abr. speed for writeing.</Description>
				</Slot>
				<Slot name="error" type="DWord" mode="r">
					<Description lang="de">Zähler der Übertragungsfehler.</Description>
					<Description lang="en">Counter for transmission-errors.</Description>
				</Slot>
			</NameSpace>
		</Provide>
    </Head>

    
    <Setup>
        <Load name="Master.Interface.UniSerial">
            <Parameter name="Port"><Variable name="Port"/></Parameter>
            <Parameter name="TimeOut">1.0</Parameter>
			<Parameter name="Parity">Even</Parameter>
            <Parameter name="Speed">9600</Parameter>
            <Load name="Master.Transport.PPI">
				<Parameter name="Address"><Variable name="PCAddr"/></Parameter>
				<Load name="Master.Debug.Statistic" namespace="PPIStatistic">
					<Address><Variable name="S7Addr"/></Address>
					<Load name="Master.Device.S7" namespace="Marker">
						<Address>tunnel</Address>
					</Load>
				</Load>
			</Load>
        </Load>
    </Setup>
        
</PPLTDevice>
