=== BackupTheBerlios/pplt-svn/PPLT/Doc/DTD/PPLT-Server-0.1.dtd
<!ELEMENT PPLTServer (Head, Setup)>
	<!ELEMENT Head (Description*, Require)>
	 
		<!ELEMENT Description (#PCDATA)>
	
		<!ELEMENT Require (DCPUModule+, Variable*)>
			<!ELEMENT DCPUModule (#PCDATA)>
			<!ELEMENT Variable (Description*)>


	<!ELEMENT Setup (Load+)>
		<!ELEMENT Load (Parameter*)>
			<!ELEMENT Address (#PCDATA | Variable)*>
			<!ELEMENT Parameter (#PCDATA?)>
		



<!ATTLIST PPLTServer
 name	CDATA	#REQUIRED
 class	CDATA	#REQUIRED
>

<!ATTLIST Description
 lang	CDATA	#REQUIRED
>

<!ATTLIST Variable
 name		CDATA	#REQUIRED
 default	CDATA	#IMPLIED
>

<!ATTLIST Load
 name		CDATA	#REQUIRED
 namespace 	CDATA	#IMPLIED
>

<!ATTLIST Parameter
 name	CDATA	#REQUIRED
 var	CDATA	#IMPLIED
>

=== BackupTheBerlios/pplt-svn/PPLT/Modules/PPLT/SimpleExportServer-0.2.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTServer SYSTEM "PPLT-Server-0.1.dtd">
<PPLTServer name="SimpleExport" class="RPC" version="0.3.0">
	<Head>
		<Description lang="de">Exportiert den Symbolbaum mittels eines XML-RPC
		Servers. Welche Methoden ihnen zur Verf√ºgung stehen, lesen sie bitte
		in der Dukumentation.</Description>
		<Description lang="en">Expots the symboltree via a XML-RPC serves.
		For what methods are aviable, read the documentation.</Description>

		<Require>
			<DCPUModule>Export.SimpleExport</DCPUModule>
			<Variable name="Address" default="127.0.0.1">
				<Description lang="de">Geben sie hier die Adresse der 
				Schnitstelle an, auf dem der Server auf neue Verbindungen 
				warten soll.</Description>
				<Description lang="en">Put here the address to bind to.
				</Description>
			</Variable>
			<Variable name="Port" default="4711">
				<Description lang="de">Geben sie hier den Port an, auf dem der
				Server auf neue Verbindungen warten soll.</Description>
				<Description lang="en">Put here the port to bind to.
				</Description>
			</Variable>
		</Require>
	</Head>

	<Setup>
		<Load name="Server.SimpleExport">
			<Parameter name="Address"><Variable name="Address"/></Parameter>
			<Parameter name="Port"><Variable name="Port"/></Parameter>
		</Load>
	</Setup>
</PPLTServer>

=== BackupTheBerlios/pplt-svn/PPLT/ftp/PPLTModules/JVisuServer-0.3.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTServer SYSTEM "PPLT-Server-0.1.dtd">
<PPLTServer name="JVisuServer" class="Visu" version="0.3.0">
	<Head>
		<Description lang="de">Mit diesem Server können sie den Symbolbaum
		für die JVisu Visualisierung exportieren.</Description>
		<Description lang="en">With this Server you can export the Symboltree
		for the JVisu visualisation.</Description>

		<Require>
			<DCPUModule>Export.JVisu</DCPUModule>
			<Variable name="Address" default="127.0.0.1">
				<Description lang="de">Geben sie hier die Adresse der 
				Schnitstelle an, auf dem der Server auf neue Verbindungen 
				warten soll.</Description>
				<Description lang="en">Put here the address to bind to.
				</Description>
			</Variable>
			<Variable name="Port" default="2200">
				<Description lang="de">Geben sie hier den Port an, auf dem der
				Server auf neue Verbindungen warten soll.</Description>
				<Description lang="en">Put here the port to bind to.
				</Description>
			</Variable>
		</Require>
	</Head>
	
	<Setup>
		<Load name="Export.JVisu">
			<Parameter name="Address"><Variable name="Address"/></Parameter>
			<Parameter name="Port"><Variable name="Port"/></Parameter>
		</Load>
	</Setup>
</PPLTServer>

=== BackupTheBerlios/pplt-svn/PPLT/ftp/PPLTModules/PPLTWebServer-0.3.xml
<?xml version="1.0"?>
<!DOCTYPE PPLTServer SYSTEM "PPLT-Server-0.1.dtd">
<PPLTServer name="PPLTWebServer" class="Web" verision="0.3.0">
	<Head>
		<Description lang="de">Mit diesem Server können sie den Symbolbaum über
		einen Webserver exportieren und dan mit ihrem Browser darauf zu 
		greifen.</Description>
		<Description lang="en">With this server you can export the symboltree
		as an webserver. Then you can browse the through the symboltree with
		you favorite FireFox.</Description>

		<Require>
			<DCPUModule>Export.PPLTWeb</DCPUModule>
			<Variable name="Address" default="127.0.0.1">
				<Description lang="de">Geben sie hier die Adresse der 
				Schnitstelle an, auf dem der Server auf neue Verbindungen 
				warten soll.</Description>
				<Description lang="en">Put here the address to bind to.
				</Description>
			</Variable>
			<Variable name="Port" default="8080">
				<Description lang="de">Geben sie hier den Port an, auf dem der
				Server auf neue Verbindungen warten soll.</Description>
				<Description lang="en">Put here the port to bind to.
				</Description>
			</Variable>
		</Require>
	</Head>

	<Setup>
		<Load name="Export.PPLTWeb">
			<Parameter name="Address"><Variable name="Address"/></Parameter>
			<Parameter name="Port"><Variable name="Port"/></Parameter>
		</Load>
	</Setup>
</PPLTServer>
